// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBx6N77LtvKhJDfrRANhDTqZAvqcRaxWsg',
    appId: '1:346486637648:web:8ebfb41d431b6210737d55',
    messagingSenderId: '346486637648',
    projectId: 'quantum-it-solutions',
    authDomain: 'quantum-it-solutions.firebaseapp.com',
    storageBucket: 'quantum-it-solutions.appspot.com',
    measurementId: 'G-VCGP7PDKDX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDm-JFoiXdu2jvwJNJTf-teF1NKnCwyNQ',
    appId: '1:346486637648:android:d7840cafad60a150737d55',
    messagingSenderId: '346486637648',
    projectId: 'quantum-it-solutions',
    storageBucket: 'quantum-it-solutions.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfo-1IChQZKNgm4BFU6mgVeuE4girZkT4',
    appId: '1:346486637648:ios:d7f432e8dc79af00737d55',
    messagingSenderId: '346486637648',
    projectId: 'quantum-it-solutions',
    storageBucket: 'quantum-it-solutions.appspot.com',
    iosClientId: '346486637648-0iag9k94rq03m02qbscsn2v8rdkkfpal.apps.googleusercontent.com',
    iosBundleId: 'com.example.assignmentApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfo-1IChQZKNgm4BFU6mgVeuE4girZkT4',
    appId: '1:346486637648:ios:d7f432e8dc79af00737d55',
    messagingSenderId: '346486637648',
    projectId: 'quantum-it-solutions',
    storageBucket: 'quantum-it-solutions.appspot.com',
    iosClientId: '346486637648-0iag9k94rq03m02qbscsn2v8rdkkfpal.apps.googleusercontent.com',
    iosBundleId: 'com.example.assignmentApplication',
  );
}
